---
title: "Limpieza"
output: html_document
date: "2024-11-19"
---

```{r, warning=FALSE, message=F}
library(tidyverse)
library(readxl)
library(lubridate)
```


# Limpieza de datos

```{r}
## Aca solo limpo los datos para que se vean como la aprte importante del excel. 
#IPC
ipc_data <- read_excel("IPC.xlsx")[-(1:4), c(1,2)] %>% 
  rename(fecha=1, IPC=2) %>% 
  mutate(fecha=dmy(str_c("01 de ", str_replace_all(fecha, "/", " ")),
                   locale = "es"),
         IPC=as.numeric(IPC))

#Expectativas encuesta
expect_data <- read_excel("Expectativas encuesta.xlsx")[-(1:3),] 
expect_data <- rename_all(expect_data, ~ c("fecha", t(expect_data[1, ])[,1][-1]))[-1, ] %>%
  mutate(fecha=dmy(str_c(
    "01 de ",
    str_sub(fecha, end=-6),
    " ",
    str_sub(fecha, str_length(fecha)-3, str_length(fecha))), locale="es")) %>% 
  rename(promedio=2) %>% 
  mutate(promedio=as.numeric(promedio))

#Expectativas mercado
expect_merc_data <- read_excel("expectativas mercado.xlsx")[-(1:4), ] %>%
  rename(fecha=1, expect_mercado=2) %>% 
  transmute(expect_mercado=as.numeric(expect_mercado),
            mes=str_extract(fecha, paste0("(.*?)(?=", "/", ")")),
            yr=str_extract(fecha, paste0("(?<=\\", "/", ").*"))
            ) %>% 
  transmute(fecha=dmy(str_c("01 ", mes, " ",yr), locale="es"),
            expect_mercado=expect_mercado) 

#Importadas
imports_data <- read_excel("Indice materias importadas.xlsx")[-(1:3),] 
imports_data <- rename_all(imports_data, ~ c("fecha", t(imports_data[1, ])[,1][-1]))[-1, ] %>% 
  mutate(fecha=dmy(str_c(
    "01 de ",
    str_sub(fecha, end=-6),
    " ",
    str_sub(fecha, str_length(fecha)-3, str_length(fecha))), locale="es")) %>%
  mutate(materias_import=as.numeric(Nivel)) %>% 
  dplyr::select(-c(2:4))

#Tipo de cambio
tipo_data <- read_excel("tipo cambio.xlsx")[-(1:4),] %>% 
  rename(fecha=1,compra=2,venta=3) %>% na.omit()

#TBP
df_tbp_crudo <- read_excel("../data/tbp.xlsx")
df_tbp <- df_tbp_crudo[-(1:3), ]
names(df_tbp) <- c( "fecha",unlist(df_tbp[1, ])[-1] %>% unname)

expect_data  #Bien
imports_data  #Bien
ipc_data  #Bien
expect_merc_data  #Bien
pib_data #Bien
tipo_data
```

# Transformacion de datos

```{r}
#Aca transformo los datos para obtener las variables que nos interesan.
ipc_mod2 <- 
  na.omit(mutate(ipc_data, inf_ipc=log(IPC)-log(dplyr::lag(IPC,1)))) #REVISAR ESTO PLZ!!!!!
  
expect_mod2 <-
  mutate(expect_data, expect= promedio) 
 
imports_mod2 <- 
  mutate(imports_data, inf_import=log(materias_import)-log(dplyr::lag(materias_import,1)))
  

expect_merc_mod2 <- expect_merc_data 



spanish_month_to_num <- function(spanish_month) {
  match(spanish_month, spanish_months)
}

spanish_months <- c('Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun', 'Jul', 'Ago', 'Set', 'Oct', 'Nov', 'Dic')
# Convert strings to dates
converted_dates <- sapply(strsplit(tipo_data$fecha, " "), function(date_parts) {
  day <- as.numeric(date_parts[1])
  month <- spanish_month_to_num(date_parts[2])
  year <- as.numeric(date_parts[3])
  # Create Date object
  fechas <- as.Date(paste(year, month, day, sep = "-"), format = "%Y-%m-%d")
  fechas
})

tipo_mod2 <- tipo_data %>%
  mutate(fecha=as.Date(converted_dates))



# TBP ####################################################################################
df_tbp <- df_tbp %>%
  slice(-1) %>%
  select(-2) %>%
  pivot_longer(names_to = "yr", values_to = "tbp", cols = -1) %>%
  mutate(tbp=as.numeric(tbp)/100, #Paso a decimales. 
         yr=as.integer(yr),
         mes=months_char_to_num(str_sub(fecha, -3)),
         dia=as.numeric(str_sub(fecha, 1, 2))) 
```
